spring.application.name=keycloak-IAM3
server.port=8083

# JWT
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/keycloakIAM

# Keycloak Admin API
keycloak.auth-server-url=http://localhost:8080
keycloak.realm=keycloakIAM
keycloak.admin.client-id=app.v3
#keycloak.admin.client-secret=u5Y7JXrfRkaAbOvpAtIXLLMt2pKYSXsr

# Disable audience validation (safe for dev; optional for prod)
#spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/keycloakIAM/protocol/openid-connect/certs

# Audit logging
logging.level.AUDIT=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n